
inherit_from:
  - .rubocop_airbnb.yml
  - .rubocop_todo.yml

# 文字数の上限を150字に変更
Metrics/LineLength:
  Max: 150
  Exclude:
    - 'config/routes.rb'

# include is used at the top level. Use inside class or module.を許可
Style/MixinUsage:
  Enabled: false

# ポストモデルのdefault scopeを許可（並び替え）
Airbnb/DefaultScope:
  Exclude:
    - 'app/models/post.rb'

# Instead of attr_name MyClass::MY_CONST, use attr_nameを許可
Airbnb/FactoryAttrReferencesClass:
  Enabled: false
