inherit_from:
  - .rubocop_airbnb.yml
  - .rubocop_todo.yml

# 文字数の上限を150字に変更
Metrics/LineLength:
  Max: 130

# include is used at the top level. Use inside class or module.を許可
Style/MixinUsage:
  Enabled: false
